"""Initial schema

Revision ID: 845e135f8e75
Revises:
Create Date: 2025-11-09 12:16:55.432781

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "845e135f8e75"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leaderboard",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("direction", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        "idx_leaderboards_active", "leaderboard", ["is_active"], unique=False
    )  # noqa: E501
    op.create_index(
        "idx_leaderboards_hash", "leaderboard", ["content_hash"], unique=False
    )  # noqa: E501
    op.create_index(
        "idx_leaderboards_updated", "leaderboard", ["updated_at"], unique=False
    )  # noqa: E501
    op.create_table(
        "user",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("snils_id", sa.String(length=14), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_rating",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("leaderboard_id", sa.String(length=36), nullable=False),
        sa.Column("place", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["leaderboard_id"],
            ["leaderboard.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "leaderboard_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_rating")
    op.drop_table("user")
    op.drop_index("idx_leaderboards_updated", table_name="leaderboard")
    op.drop_index("idx_leaderboards_hash", table_name="leaderboard")
    op.drop_index("idx_leaderboards_active", table_name="leaderboard")
    op.drop_table("leaderboard")
    # ### end Alembic commands ###
