"""make_snils_nullable

Revision ID: 616d89ebe0b5
Revises: 845e135f8e75
Create Date: 2025-12-02 21:10:33.099339

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "616d89ebe0b5"
down_revision: Union[str, Sequence[str], None] = "845e135f8e75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "snils_id", existing_type=sa.VARCHAR(length=14), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "snils_id", existing_type=sa.VARCHAR(length=14), nullable=False
    )
    # ### end Alembic commands ###
