"""add faq_entry and abbreviation tables

Revision ID: d267a76e1a85
Revises: 2a3b4c5d6e7f
Create Date: 2026-05-11 12:59:00.139943

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd267a76e1a85'
down_revision: Union[str, Sequence[str], None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abbreviation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('short', sa.String(length=50), nullable=False),
    sa.Column('full', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short')
    )
    op.create_index('idx_abbreviation_short', 'abbreviation', ['short'], unique=False)
    op.create_table('faq_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_entry')
    op.drop_index('idx_abbreviation_short', table_name='abbreviation')
    op.drop_table('abbreviation')
    # ### end Alembic commands ###
