parser:
  url: "https://education.nsu.ru/"
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  faculties:
    os: "oriental_studies"
    fl: "foreign_languages"
    jour: "journalism"
    his: "history"
    phi: "philology"
    ling: "linguistics"
    med: "medicine"
    psy: "psychology"
    ppl_ph: "ppl_philosophy"
    ppl_law: "ppl_law"
    phy: "physics"
    math: "mathematics"
    nat_sci: "naturalsciences"
    it: "information-technologies"
    eco: "economics"
    geo: "geology"
    mech: "mechatronics"
    ai: "ai"
    eng_sch: "engineering_school"
  selectors:
    - style: "div"
      attr: "tn-atom"
    - style: "div"
      attr: "t-card__title"
    - style: "div"
      attr: "t-card__descr"
    - style: "h1"
      attr: "tn-atom"
    - style: "h2"
      attr: "tn-atom"
    - style: "span"
    - style: "strong"
    - style: "div"
      attr: "t195__text"
    - style: "div"
      attr: "t497__descr"
    - style: "div"
      attr: "t-text"
